name: telco-churn-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas==2.1.4
      - numpy==1.26.2
      - scikit-learn==1.3.2
      - mlflow==2.19.0
      - matplotlib
      - seaborn
